language: node_js
node_js:
  - "6"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - yarn run build

after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}
