language: node_js
node_js:
  - "6"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - yarn run build

after_success:
  - firebase use --token ${FIREBASE_DEPLOY_KEY} {$PROJECT_NAME}
  - firebase deploy --token ${FIREBASE_DEPLOY_KEY}
